users:
  toyesh:
    display_name: Toyesh
    databases:
    - chinook
    - northwind
    - sakila
  alfred:
    display_name: Alfred
    databases:
    - chinook
  donne:
    display_name: Donné
    databases: []
